#!/usr/bin/env bash

sudo apt install xorg \
                 openbox \
                 obconf \
                 obmenu \
                 lxappearance \
                 lxappearance-obconf \
                 gmrun \
                 xfce4-terminal \
                 pcmanfm \
                 gvfs-backends \
                 gvfs-fuse \
                 xarchiver \
                 p7zip-full \
                 rar \
                 unrar \
                 wicd-gtk \
                 wicd-curses \
                 wicd-cli \
                 compton \
                 numlockx \
                 inxi \
                 wmctrl \
                 xdotool \
                 htop \
                 neofetch \
                 nitrogen \
                 arandr \
                 fzf \
                 suckless-tools \
                 rofi \
                 pavucontrol \
                 pulseaudio-utils \
                 papirus-icon-theme \
                 arc-theme \
                 numix-gtk-theme \
                 numix-icon-theme \
                 numix-icon-theme-circle \
                 breeze-cursor-theme \
                 xfce4-panel \
                 xfce4-datetime-plugin \
                 xfce4-whiskermenu-plugin \
                 xfce4-genmon-plugin \
                 xfce4-pulseaudio-plugin \
                 xfce4-screenshooter \
                 xfce4-power-manager \
                 lxinput \
                 menulibre \
                 mousepad \
                 ttf-mscorefonts-installer \
                 poppler-utils \
                 policykit-1-gnome
